dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - wget
      - pkg-config

# Eventually, Bazel will have binary packages and we'll be able to
# just download a prebuilt distribution of Bazel. For now, build it
# from source every time.
before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.3.1/bazel_0.3.1-linux-x86_64.deb
  - sha256sum -c ci/bazel_0.3.1-linux-x86_64.deb.sha256
  - sudo dpkg -i bazel_0.3.1-linux-x86_64.deb

script:
  - cp ci/bazelrc code/.bazelrc
  - cd code
  - bazel build //prototype:...
#  - bazel test --test_output=streamed //prototype/lib:all
#  - bazel test //...
