apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: corenlp-deployment
spec:
  selector:
    matchLabels:
      app: corenlp
  replicas: 4
  template:
    metadata:
      labels:
        app: corenlp
    spec:
      containers:
      - name: corenlp
        image: nlpbox/corenlp
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
