apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: corenlp-deployment
spec:
  selector:
    matchLabels:
      app: corenlp
  replicas: 2
  template:
    metadata:
      labels:
        app: corenlp
    spec:
      containers:
      - name: corenlp
        image: gcr.io/extended-atrium-198523/corenlp
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: "1"
            memory: 6Gi
