apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: dbpedia-spotlight-deployment
spec:
  selector:
    matchLabels:
      app: dbpedia-spotlight
  replicas: 2
  template:
    metadata:
      labels:
        app: dbpedia-spotlight
    spec:
      containers:
      - name: dbpedia-spotlight
        # TODO(prvak): Use own container?
        image: dbpedia/spotlight-english
        command: ["spotlight.sh"]
        #:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "1"
            memory: 8Gi

