apiVersion: batch/v1
kind: Job
metadata:
  name: create-single-file
  labels:
    app: create-single-file
spec:
  template:
    metadata:
      labels:
        app: create-single-file
        tier: worker
    spec:
      containers:
      - name: create-single-file
        image: gcr.io/extended-atrium-198523/create_single_file
        imagePullPolicy: Always
      restartPolicy: OnFailure
