apiVersion: batch/v1
kind: Job
metadata:
  name: create-single-file
spec:
  template:
    spec:
      containers:
      - name: create-single-file
        image: gcr.io/extended-atrium-198523/create_single_file
        imagePullPolicy: Always
      restartPolicy: OnFailure
