apiVersion: batch/v1
kind: Job
metadata:
  name: upload-to-storage
spec:
  template:
    spec:
      containers:
      - name: upload-to-storage
        image: gcr.io/extended-atrium-198523/upload_to_storage
        imagePullPolicy: Always
      restartPolicy: OnFailure
